// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: HelloWorld.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace SSD.ATLASti.Common.HelloWorld.Model {
  public static partial class HelloWorldService
  {
    static readonly string __ServiceName = "atlasti.HelloWorldService";

    static readonly grpc::Marshaller<global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloAgainActionRequest> __Marshaller_atlasti_SayHelloAgainActionRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloAgainActionRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloAgainActionReply> __Marshaller_atlasti_SayHelloAgainActionReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloAgainActionReply.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloActionRequest> __Marshaller_atlasti_SayHelloActionRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloActionRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloActionReply> __Marshaller_atlasti_SayHelloActionReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloActionReply.Parser.ParseFrom);

    static readonly grpc::Method<global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloAgainActionRequest, global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloAgainActionReply> __Method_SayHelloAgain = new grpc::Method<global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloAgainActionRequest, global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloAgainActionReply>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "SayHelloAgain",
        __Marshaller_atlasti_SayHelloAgainActionRequest,
        __Marshaller_atlasti_SayHelloAgainActionReply);

    static readonly grpc::Method<global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloActionRequest, global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloActionReply> __Method_SayHello = new grpc::Method<global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloActionRequest, global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloActionReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SayHello",
        __Marshaller_atlasti_SayHelloActionRequest,
        __Marshaller_atlasti_SayHelloActionReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::SSD.ATLASti.Common.HelloWorld.Model.HelloWorldReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of HelloWorldService</summary>
    public abstract partial class HelloWorldServiceBase
    {
      public virtual global::System.Threading.Tasks.Task SayHelloAgain(global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloAgainActionRequest request, grpc::IServerStreamWriter<global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloAgainActionReply> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloActionReply> SayHello(global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloActionRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for HelloWorldService</summary>
    public partial class HelloWorldServiceClient : grpc::ClientBase<HelloWorldServiceClient>
    {
      /// <summary>Creates a new client for HelloWorldService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public HelloWorldServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for HelloWorldService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public HelloWorldServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected HelloWorldServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected HelloWorldServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloAgainActionReply> SayHelloAgain(global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloAgainActionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHelloAgain(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloAgainActionReply> SayHelloAgain(global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloAgainActionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_SayHelloAgain, null, options, request);
      }
      public virtual global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloActionReply SayHello(global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloActionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHello(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloActionReply SayHello(global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloActionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SayHello, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloActionReply> SayHelloAsync(global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloActionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHelloAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloActionReply> SayHelloAsync(global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloActionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SayHello, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override HelloWorldServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new HelloWorldServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(HelloWorldServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SayHelloAgain, serviceImpl.SayHelloAgain)
          .AddMethod(__Method_SayHello, serviceImpl.SayHello).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, HelloWorldServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_SayHelloAgain, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloAgainActionRequest, global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloAgainActionReply>(serviceImpl.SayHelloAgain));
      serviceBinder.AddMethod(__Method_SayHello, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloActionRequest, global::SSD.ATLASti.Common.HelloWorld.Model.SayHelloActionReply>(serviceImpl.SayHello));
    }

  }
}
#endregion
