source 'https://github.com/CocoaPods/Specs.git'
platform :macos, '10.12'

install! 'cocoapods', :deterministic_uuids => false

target 'HelloWorldManager' do
  # Depend on the generated HelloWorldManager framework.
  project 'HelloWorldManager.xcodeproj'
  pod 'HelloWorldManager', :path => '.'
end
